{
 "title": "App Overview",
 "panels": [
  {
   "title": "Targets UP",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Requests por segundo (RPS)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 3 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count[1m]))"
    }
   ]
  },
  {
   "title": "Erros 4xx",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 3 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count{code=~\"4..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Erros 5xx",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 3 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count{code=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latência HTTP (P95)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 3, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Latência HTTP (P99)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 3, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_ms_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m]) * 100"
    }
   ]
  },
  {
   "title": "Uso de memória",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 11, "w": 12, "h": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  }
 ]
}