global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ecs-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rodrigo-alb-backend-1568030242.us-east-2.elb.amazonaws.com:3000']