name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'
  # Permite que o pipeline de Infra chame este aqui assim que terminar
  workflow_run:
    workflows: ["Infraestrutura (Terraform)"]
    types:
      - completed
  workflow_dispatch: # Permite execução manual

jobs:
  deploy-frontend:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # -----------------------------------------------------------
      # Ler os Outputs da Infraestrutura
      # -----------------------------------------------------------
      - name: Configurar AWS e Ler Infra
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform (Apenas para ler outputs)
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Carregar Variáveis da Infra
        id: infra
        working-directory: ./terraform
        run: |
          terraform init
          echo "s3_bucket=$(terraform output -raw s3_frontend_bucket)" >> $GITHUB_OUTPUT

      # -----------------------------------------------------------
      # Deploy FRONTEND
      # -----------------------------------------------------------
      - name: Install & Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Upload Frontend para S3
        run: |
          aws s3 sync ./frontend/dist s3://${{ steps.infra.outputs.s3_bucket }} --delete

      - name: Invalidar Cache do CloudFront (Opcional)
        run: |
          # DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id)
          # aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

